-- AlterTable
ALTER TABLE "invoices" ADD COLUMN     "contract_no" TEXT,
ADD COLUMN     "contract_period" TEXT,
ADD COLUMN     "contract_subject" TEXT,
ADD COLUMN     "pay_bank_address" TEXT,
ADD COLUMN     "pay_swift" TEXT,
ADD COLUMN     "payee_address" TEXT,
ADD COLUMN     "payee_bin" TEXT,
ADD COLUMN     "payee_country" TEXT,
ADD COLUMN     "payee_email" TEXT,
ADD COLUMN     "payee_firm" TEXT,
ADD COLUMN     "payee_name" TEXT,
ADD COLUMN     "payee_work_type" TEXT,
ADD COLUMN     "recipient_address" TEXT,
ADD COLUMN     "recipient_attention" TEXT,
ADD COLUMN     "recipient_bin" TEXT,
ADD COLUMN     "recipient_email" TEXT,
ADD COLUMN     "recipient_name" TEXT,
ADD COLUMN     "recipient_phone" TEXT;
